import { useCallback, useEffect, useMemo, useState } from 'react'
import { exportCourierIssues, getCourierIssueOptions, getCourierIssues, saveCourierIssue, type CourierIssue, type CourierIssueFilters, type CourierIssueOptions, type CourierIssuePayload, type CourierIssueStatus } from '../services/courierIssues'
import { ageTone, localToday, sortCourierIssues, type CourierIssueSort } from '../utils/courierIssues'

const emptyOptions: CourierIssueOptions = { raised_by: [], couriers: [], issue_types: [] }
const blank = (raisedBy = ''): CourierIssuePayload => ({ awb: '', date_raised: localToday(), raised_by: raisedBy, courier: '', issue_type: '', notes: '', status: 'open', closure_date: null })
const input = 'w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-orange-300 focus:ring-2 focus:ring-orange-100'

export function CourierIssuesPage({ currentUser, onOpenOrder }: { currentUser: string; onOpenOrder: (orderId: string, orderNumber: string) => void }) {
  const [status, setStatus] = useState<CourierIssueStatus>('open')
  const [filters, setFilters] = useState<Omit<CourierIssueFilters, 'status'>>({ search: '', courier: '', issue_type: '', raised_by: '' })
  const [items, setItems] = useState<CourierIssue[]>([])
  const [kpis, setKpis] = useState({ open: 0, open_over_7: 0, open_over_15: 0, closed_this_month: 0 })
  const [options, setOptions] = useState(emptyOptions)
  const [sort, setSort] = useState<CourierIssueSort>('age_desc')
  const [editing, setEditing] = useState<CourierIssue | null | undefined>(undefined)
  const [draft, setDraft] = useState<CourierIssuePayload>(blank(currentUser))
  const [error, setError] = useState('')
  const currentFilters = useMemo(() => ({ status, ...filters }), [status, filters])
  const load = useCallback(() => void getCourierIssues(currentFilters).then(result => { setItems(result.items); setKpis(result.kpis); setError('') }).catch(value => setError(value.message)), [currentFilters])

  useEffect(() => { void getCourierIssueOptions().then(value => { setOptions(value); setDraft(current => ({ ...current, raised_by: current.raised_by || currentUser || value.raised_by[0] || '' })) }).catch(value => setError(value.message)) }, [currentUser])
  useEffect(load, [load])
  const displayed = useMemo(() => sortCourierIssues(items, sort), [items, sort])
  const begin = (issue?: CourierIssue) => { setEditing(issue || null); setDraft(issue ? { awb: issue.awb, date_raised: issue.date_raised, raised_by: issue.raised_by, courier: issue.courier, issue_type: issue.issue_type, notes: issue.notes || '', status: issue.status, closure_date: issue.closure_date } : blank(currentUser)); setError('') }
  const persist = async () => { try { await saveCourierIssue(draft, editing?.id); setEditing(undefined); load() } catch (value) { setError((value as Error).message) } }
  const changeStatus = async (issue: CourierIssue, next: CourierIssueStatus) => { try { await saveCourierIssue({ awb: issue.awb, date_raised: issue.date_raised, raised_by: issue.raised_by, courier: issue.courier, issue_type: issue.issue_type, notes: issue.notes, status: next, closure_date: next === 'closed' ? localToday() : null }, issue.id); load() } catch (value) { setError((value as Error).message) } }

  return <div>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2" aria-label="Courier issue status"><button onClick={() => setStatus('open')} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${status === 'open' ? 'bg-slate-900 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>Open</button><button onClick={() => setStatus('closed')} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${status === 'closed' ? 'bg-slate-900 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>Closed</button></div><div className="flex gap-2"><button onClick={() => void exportCourierIssues(currentFilters).catch(value => setError(value.message))} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-600">Export Excel</button><button onClick={() => begin()} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">+ Add Issue</button></div></div>
    <div className="mb-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{[['Open Issues', kpis.open], ['Open >7 Days', kpis.open_over_7], ['Open >15 Days', kpis.open_over_15], ['Closed This Month', kpis.closed_this_month]].map(([label, value]) => <div key={label} className="rounded-lg border border-slate-200 bg-white px-3 py-2"><p className="text-[11px] font-semibold text-slate-500">{label}</p><p className="text-lg font-bold text-slate-900">{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b border-slate-200 p-3"><input aria-label="Search AWB" value={filters.search} onChange={event => setFilters(value => ({ ...value, search: event.target.value }))} placeholder="Search AWB" className={`${input} max-w-52`} />{([['courier', 'All couriers', options.couriers], ['issue_type', 'All issue types', options.issue_types], ['raised_by', 'All team members', options.raised_by]] as const).map(([key, label, values]) => <select aria-label={label} key={key} value={filters[key]} onChange={event => setFilters(current => ({ ...current, [key]: event.target.value }))} className={`${input} w-auto`}><option value="">{label}</option>{values.map(value => <option key={value}>{value}</option>)}</select>)}<select aria-label="Sort issues" value={sort} onChange={event => setSort(event.target.value as CourierIssueSort)} className={`${input} ml-auto w-auto`}><option value="age_desc">Oldest first</option><option value="age_asc">Newest first</option><option value="awb">AWB</option><option value="courier">Courier</option></select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">AWB</th><th>Date Raised</th>{status === 'closed' && <th>Closure Date</th>}<th>Age</th><th>Raised By</th><th>Courier</th><th>Issue Type</th><th>Notes</th><th>Status</th><th>Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{displayed.map(issue => { const tone = ageTone(issue.age); return <tr key={issue.id}><td className="px-3 py-3 font-mono text-xs">{issue.order_id && issue.order_number ? <button className="font-semibold text-orange-600 hover:underline" onClick={() => onOpenOrder(issue.order_id!, issue.order_number!)}>{issue.awb}</button> : issue.awb}</td><td>{issue.date_raised}</td>{status === 'closed' && <td>{issue.closure_date || '—'}</td>}<td><span className={`rounded px-1.5 py-1 font-semibold ${tone === 'critical' ? 'bg-rose-50 text-rose-700' : tone === 'warning' ? 'bg-amber-50 text-amber-700' : 'text-slate-600'}`}>{issue.age}d</span></td><td>{issue.raised_by}</td><td>{issue.courier}</td><td>{issue.issue_type}</td><td className="max-w-xs whitespace-pre-wrap text-slate-600">{issue.notes || '—'}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${issue.status === 'open' ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'}`}>{issue.status === 'open' ? 'Open' : 'Closed'}</span></td><td><div className="flex gap-2"><button onClick={() => begin(issue)} className="text-xs font-semibold text-slate-600">Edit</button><button onClick={() => void changeStatus(issue, issue.status === 'open' ? 'closed' : 'open')} className="text-xs font-semibold text-orange-600">{issue.status === 'open' ? 'Close' : 'Reopen'}</button></div></td></tr>})}</tbody></table>{!displayed.length && <p className="py-12 text-center text-sm text-slate-400">No {status} courier issues match the filters.</p>}</div>
    </section>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}
    {editing !== undefined && <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={event => { event.preventDefault(); void persist() }} className="w-full max-w-2xl rounded-xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-lg font-bold">{editing ? 'Edit Courier Issue' : 'Add Courier Issue'}</h3><button type="button" onClick={() => setEditing(undefined)} className="text-slate-400">×</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">AWB<input required value={draft.awb} onChange={event => setDraft(value => ({ ...value, awb: event.target.value }))} className={input} /></label><label className="text-sm">Date Raised<input aria-label="Date Raised" required type="date" value={draft.date_raised} onChange={event => setDraft(value => ({ ...value, date_raised: event.target.value }))} className={input} /></label><label className="text-sm">Raised By<select required value={draft.raised_by} onChange={event => setDraft(value => ({ ...value, raised_by: event.target.value }))} className={input}><option value="">Select</option>{options.raised_by.map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Courier<select required value={draft.courier} onChange={event => setDraft(value => ({ ...value, courier: event.target.value }))} className={input}><option value="">Select</option>{options.couriers.map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Issue Type<select required value={draft.issue_type} onChange={event => setDraft(value => ({ ...value, issue_type: event.target.value }))} className={input}><option value="">Select</option>{options.issue_types.map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Status<select value={draft.status} onChange={event => setDraft(value => ({ ...value, status: event.target.value as CourierIssueStatus, closure_date: event.target.value === 'closed' ? value.closure_date || localToday() : null }))} className={input}><option value="open">Open</option><option value="closed">Closed</option></select></label>{draft.status === 'closed' && <label className="text-sm">Closure Date<input type="date" required value={draft.closure_date || ''} onChange={event => setDraft(value => ({ ...value, closure_date: event.target.value }))} className={input} /></label>}<label className="text-sm sm:col-span-2">Notes<textarea rows={3} value={draft.notes || ''} onChange={event => setDraft(value => ({ ...value, notes: event.target.value }))} className={input} /></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setEditing(undefined)} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600">Cancel</button><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Save Issue</button></div></form></div>}
  </div>
}
