import { useEffect, useState } from 'react'

import { getUsers, resetUserPassword, updateUser, type ManagedUser, type UserRole } from '../services/users'

export function UsersPage() {
  const [users, setUsers] = useState<ManagedUser[]>([])
  const [resetId, setResetId] = useState<number | null>(null)
  const [password, setPassword] = useState('')
  const [confirmation, setConfirmation] = useState('')
  const [notice, setNotice] = useState('')
  const refresh = () => void getUsers().then(setUsers).catch(error => setNotice(error.message))
  useEffect(refresh, [])
  const replace = (user: ManagedUser) => setUsers(current => current.map(value => value.id === user.id ? user : value))
  return <div>
    <div className="mb-5"><p className="text-sm font-medium text-[#ff6b35]">Settings</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Users</h2><p className="mt-1 text-sm text-slate-500">Manage access, roles, and password resets.</p></div>
    {notice && <p role="status" className="mb-4 rounded-lg bg-slate-100 px-3 py-2 text-sm text-slate-700">{notice}</p>}
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last login</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map(user => <tr key={user.id}><td className="px-4 py-3"><p className="font-semibold text-slate-800">{user.display_name}</p><p className="text-xs text-slate-400">{user.username}</p></td><td className="px-4 py-3"><select aria-label={`Role for ${user.username}`} disabled={user.role === 'owner'} value={user.role} onChange={event => void updateUser(user.id, { role: event.target.value as UserRole }).then(replace).catch(error => setNotice(error.message))} className="rounded-md border border-slate-200 px-2 py-1.5"><option value="owner">Owner</option><option value="admin">Admin</option><option value="operator">Operator</option></select></td><td className="px-4 py-3">{user.is_active ? 'Active' : 'Inactive'}</td><td className="px-4 py-3 text-xs text-slate-500">{user.last_login_at ? new Date(user.last_login_at).toLocaleString('en-IN') : 'Never'}</td><td className="px-4 py-3"><div className="flex gap-2"><button disabled={user.role === 'owner'} onClick={() => void updateUser(user.id, { is_active: !user.is_active }).then(replace).catch(error => setNotice(error.message))} className="rounded-md border border-slate-200 px-2 py-1.5 text-xs font-semibold disabled:opacity-40">{user.is_active ? 'Deactivate' : 'Activate'}</button><button onClick={() => { setResetId(user.id); setPassword(''); setConfirmation('') }} className="rounded-md border border-slate-200 px-2 py-1.5 text-xs font-semibold">Reset password</button></div></td></tr>)}</tbody></table></section>
    {resetId !== null && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={event => { event.preventDefault(); void resetUserPassword(resetId, password, confirmation).then(() => { setResetId(null); setNotice('Password reset successfully.') }).catch(error => setNotice(error.message)) }} className="w-full max-w-sm rounded-xl bg-white p-5 shadow-xl"><h3 className="text-lg font-bold">Reset password</h3><label className="mt-4 block text-sm">New password<input autoComplete="new-password" type="password" minLength={12} required value={password} onChange={event => setPassword(event.target.value)} className="mt-1 w-full rounded-md border border-slate-200 px-3 py-2" /></label><label className="mt-3 block text-sm">Confirm password<input autoComplete="new-password" type="password" minLength={12} required value={confirmation} onChange={event => setConfirmation(event.target.value)} className="mt-1 w-full rounded-md border border-slate-200 px-3 py-2" /></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setResetId(null)} className="px-3 py-2 text-sm">Cancel</button><button className="rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Reset</button></div></form></div>}
  </div>
}
