import { apiBase, apiFetch } from './orders'
export type FinancialCase={id:string;provider:string;awb:string;order_number:string|null;courier_name:string|null;primary_issue_type:string|null;issue_summary:string|null;amount_at_risk:number;age_days:number;action_deadline:string|null;priority:string;os_status:string;expected_cod:number|null;remitted_cod:number|null;expected_freight:number|null;actual_freight:number|null;weight_excess_charge:number|null;other_debits:number|null;credits_refunds:number|null;ledger_entries?:{id:string;component:string;debit:number;credit:number;reference:string|null;invoice_or_remittance_id:string|null;date:string|null;remarks:string|null;source_row_number:number;document_id:string}[];actions?:{action:string;note:string|null;actor_name:string|null;created_at:string|null}[]}
export type FinancialSummary={needs_action:{count:number;amount:number};cod_pending:{count:number;amount:number};charge_mismatch:{count:number;amount:number};in_progress:{count:number;amount:number};recovered:number}
const fail=async(r:Response)=>{const b=await r.json().catch(()=>null);throw new Error(b?.detail||b?.message||`Request failed (HTTP ${r.status}).`)}
export async function getFinancialSummary():Promise<FinancialSummary>{const r=await apiFetch(`${apiBase}/api/v1/courier-reconciliation/summary`);if(!r.ok)await fail(r);return r.json()}
export async function getFinancialCases(filters:Record<string,string>={}):Promise<{items:FinancialCase[]}>{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const r=await apiFetch(`${apiBase}/api/v1/courier-reconciliation/cases?${q}`);if(!r.ok)await fail(r);return r.json()}
export async function getFinancialCase(id:string):Promise<FinancialCase>{const r=await apiFetch(`${apiBase}/api/v1/courier-reconciliation/cases/${id}`);if(!r.ok)await fail(r);return r.json()}
export async function actOnFinancialCase(id:string,payload:{action:string;note?:string;assigned_to_user_id?:number}){const r=await apiFetch(`${apiBase}/api/v1/courier-reconciliation/cases/${id}/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)await fail(r);return r.json()}
export async function bulkFinancialCases(payload:{case_ids:string[];action:string;assigned_to_user_id?:number}){const r=await apiFetch(`${apiBase}/api/v1/courier-reconciliation/cases/bulk-actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)await fail(r);return r.json()}
