import { apiBase, apiFetch } from './orders'

export type NDRCase = { id: string; awb: string; order_id: string | null; order_number: string | null; provider: string; courier_name: string | null; customer_name: string | null; customer_phone: string | null; customer_address: Record<string, string | null> | null; products: { product_name: string; quantity: number; price: string | number }[]; cod_amount: number; shopify_order_url: string | null; provider_tracking_url: string | null; current_status: string; provider_status: string | null; failure_reason: string | null; recommended_action: string | null; priority: string; delivery_attempts: number; assigned_to_user_id: number | null; assigned_to_name: string | null; first_ndr_at: string; last_provider_update_at: string | null; last_synced_at: string; customer_contacted_at: string | null; courier_contacted_at: string | null; resolved_at: string | null; resolution_note: string | null; ageing_hours: number; over_sla: boolean; events?: NDREvent[] }
export type NDREvent = { id: string; event_type: string; description: string; actor_name: string | null; event_data: Record<string, unknown> | null; created_at: string | null }
export type NDRSummary = { active_ndr: number; new_today: number; awaiting_customer: number; courier_pending: number; resolved_today: number; over_sla: number; last_sync_at: string | null; last_sync_status: string | null }
export type NDROperator = { id: number; display_name: string; username: string }
export type NDRFilters = { search?: string; courier?: string; failure_reason?: string; ageing?: string; assigned_to?: string; status?: string; priority?: string }

const error = async (response: Response) => new Error((await response.json().catch(() => null))?.detail || 'NDR request failed.')
export async function getNDRSummary(): Promise<NDRSummary> { const r = await apiFetch(`${apiBase}/api/v1/ndr/summary`); if (!r.ok) throw await error(r); return r.json() }
export async function getNDROperators(): Promise<NDROperator[]> { const r = await apiFetch(`${apiBase}/api/v1/ndr/operators`); if (!r.ok) throw await error(r); return r.json() }
export async function getNDRCases(filters: NDRFilters = {}): Promise<{ items: NDRCase[]; total: number }> { const q = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) q.set(key, value) }); const r = await apiFetch(`${apiBase}/api/v1/ndr/cases?${q}`); if (!r.ok) throw await error(r); return r.json() }
export async function getNDRCase(id: string): Promise<NDRCase> { const r = await apiFetch(`${apiBase}/api/v1/ndr/cases/${id}`); if (!r.ok) throw await error(r); return r.json() }
export async function syncNDR(): Promise<void> { const r = await apiFetch(`${apiBase}/api/v1/ndr/sync`, { method: 'POST' }); if (!r.ok) throw await error(r) }
export async function actOnNDR(id: string, payload: { action: string; note?: string; assigned_to_user_id?: number }): Promise<NDRCase> { const r = await apiFetch(`${apiBase}/api/v1/ndr/cases/${id}/actions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!r.ok) throw await error(r); return r.json() }
