"""add courier financial reconciliation tables

Revision ID: 20260907_01_financial
Revises: 20260728_04_ndr_import
"""
from alembic import op
import sqlalchemy as sa

revision = "20260907_01_financial"
down_revision = "20260728_04_ndr_import"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("courier_financial_cases", sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(32),nullable=False),sa.Column("awb",sa.String(128),nullable=False),sa.Column("order_id",sa.String(64)),sa.Column("order_number",sa.String(64)),sa.Column("courier_name",sa.String(128)),sa.Column("shipment_status",sa.String(64)),sa.Column("booked_at",sa.DateTime(timezone=True)),sa.Column("delivered_at",sa.DateTime(timezone=True)),sa.Column("rto_at",sa.DateTime(timezone=True)),sa.Column("expected_cod",sa.Float),sa.Column("expected_freight",sa.Float),sa.Column("declared_weight_g",sa.Float),sa.Column("declared_dimensions",sa.JSON),sa.Column("remitted_cod",sa.Float),sa.Column("actual_freight",sa.Float),sa.Column("weight_excess_charge",sa.Float),sa.Column("other_debits",sa.Float),sa.Column("credits_refunds",sa.Float),sa.Column("net_variance",sa.Float),sa.Column("primary_issue_type",sa.String(64)),sa.Column("issue_summary",sa.Text),sa.Column("amount_at_risk",sa.Float,server_default="0",nullable=False),sa.Column("action_deadline",sa.DateTime(timezone=True)),sa.Column("age_days",sa.Integer,server_default="0",nullable=False),sa.Column("priority",sa.String(16)),sa.Column("os_status",sa.String(32),server_default="Needs Action",nullable=False),sa.Column("assigned_to_user_id",sa.Integer,sa.ForeignKey("users.id")),sa.Column("assigned_to_name",sa.String(120)),sa.Column("action_note",sa.Text),sa.Column("last_action_at",sa.DateTime(timezone=True)),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("provider","awb",name="uq_financial_case_provider_awb"))
    op.create_table("courier_financial_documents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(32),nullable=False),sa.Column("document_type",sa.String(64),nullable=False),sa.Column("filename",sa.String(512),nullable=False),sa.Column("period",sa.String(128)),sa.Column("checksum",sa.String(64),nullable=False,unique=True),sa.Column("parser_version",sa.String(32),nullable=False),sa.Column("source_metadata",sa.JSON),sa.Column("imported_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("courier_financial_ledger_entries",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_id",sa.String(36),sa.ForeignKey("courier_financial_documents.id"),nullable=False),sa.Column("provider",sa.String(32),nullable=False),sa.Column("awb",sa.String(128)),sa.Column("component",sa.String(64),nullable=False),sa.Column("debit",sa.Float,server_default="0",nullable=False),sa.Column("credit",sa.Float,server_default="0",nullable=False),sa.Column("net_amount",sa.Float),sa.Column("tax_amount",sa.Float),sa.Column("gross_amount",sa.Float),sa.Column("provider_reference_id",sa.String(160)),sa.Column("invoice_or_remittance_id",sa.String(160)),sa.Column("occurred_at",sa.DateTime(timezone=True)),sa.Column("remarks",sa.Text),sa.Column("source_row_number",sa.Integer,nullable=False),sa.Column("source_row_hash",sa.String(64),nullable=False),sa.Column("raw_row",sa.JSON,nullable=False),sa.Column("imported_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("document_id","source_row_hash",name="uq_financial_document_row"))
    op.create_table("courier_settlements",sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(32),nullable=False),sa.Column("settlement_id",sa.String(160),nullable=False),sa.Column("processed_at",sa.DateTime(timezone=True)),sa.Column("bank_reference",sa.String(160)),sa.Column("status",sa.String(64)),sa.Column("gross_amount",sa.Float),sa.Column("deductions",sa.Float),sa.Column("net_paid",sa.Float),sa.Column("allocations",sa.JSON),sa.Column("document_id",sa.String(36),sa.ForeignKey("courier_financial_documents.id")),sa.UniqueConstraint("provider","settlement_id",name="uq_courier_settlement"))
    op.create_table("courier_financial_actions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("case_id",sa.String(36),sa.ForeignKey("courier_financial_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("action",sa.String(64),nullable=False),sa.Column("note",sa.Text),sa.Column("actor_user_id",sa.Integer,sa.ForeignKey("users.id")),sa.Column("actor_name",sa.String(120)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("courier_financial_unmatched_rows",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_id",sa.String(36),sa.ForeignKey("courier_financial_documents.id"),nullable=False),sa.Column("provider",sa.String(32),nullable=False),sa.Column("awb_or_reference",sa.String(160)),sa.Column("amount",sa.Float),sa.Column("reason",sa.String(256),nullable=False),sa.Column("source_row_number",sa.Integer,nullable=False),sa.Column("source_row_hash",sa.String(64),nullable=False),sa.Column("raw_row",sa.JSON,nullable=False))
def downgrade():
    op.drop_table("courier_financial_unmatched_rows"); op.drop_table("courier_financial_actions"); op.drop_table("courier_settlements"); op.drop_table("courier_financial_ledger_entries"); op.drop_table("courier_financial_documents"); op.drop_table("courier_financial_cases")
