import { useMemo, useState } from 'react'
import { orders, type Order } from './mock/orders'

type IconName = 'grid' | 'bag' | 'alert' | 'users' | 'chart' | 'settings' | 'search' | 'bell' | 'filter' | 'chevron' | 'more' | 'eye' | 'truck' | 'calendar' | 'menu'

const Icon = ({ name, size = 18 }: { name: IconName; size?: number }) => {
  const paths: Record<IconName, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    bag: <><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,
    alert: <><path d="M10.3 3.3 2.4 17a2 2 0 0 0 1.7 3h15.8a2 2 0 0 0 1.7-3L13.7 3.3a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    chart: <><path d="M4 19V5M4 19h17"/><path d="m7 15 4-4 3 2 5-6"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.1 2.1-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56v.1h-3v-.1A1.7 1.7 0 0 0 10.7 18.6a1.7 1.7 0 0 0-1.88.34l-.06.06-2.1-2.1.06-.06A1.7 1.7 0 0 0 7.06 15a1.7 1.7 0 0 0-1.56-1.03h-.1v-3h.1A1.7 1.7 0 0 0 7.06 9.94a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.1-2.1.06.06a1.7 1.7 0 0 0 1.88.34 1.7 1.7 0 0 0 1.03-1.56v-.1h3v.1a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.1 2.1-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.56 1.03h.1v3h-.1A1.7 1.7 0 0 0 19.4 15Z"/></>,
    search: <><circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,
    filter: <path d="M4 5h16M7 12h10M10 19h4"/>, chevron: <path d="m9 18 6-6-6-6"/>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,
    eye: <><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></>, truck: <><path d="M3 5h11v11H3zM14 9h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>, calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>, menu: <path d="M4 6h16M4 12h16M4 18h16"/>,
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}

const nav = [['grid', 'Dashboard'], ['bag', 'Orders'], ['alert', 'NDR'], ['users', 'Customers'], ['chart', 'Reports']] as const
const riskStyle = { High: 'bg-rose-50 text-rose-700 ring-rose-100', Medium: 'bg-amber-50 text-amber-700 ring-amber-100', Low: 'bg-emerald-50 text-emerald-700 ring-emerald-100' }

function App() {
  const [search, setSearch] = useState('')
  const [payment, setPayment] = useState('All payments')
  const [risk, setRisk] = useState('All risks')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const filtered = useMemo(() => orders.filter((order) => {
    const text = `${order.id} ${order.customer} ${order.city} ${order.state}`.toLowerCase()
    return text.includes(search.toLowerCase()) && (payment === 'All payments' || order.payment === payment) && (risk === 'All risks' || order.risk === risk)
  }), [search, payment, risk])
  const action = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2500) }

  return <div className="min-h-screen bg-[#f8fafc] text-slate-900">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-slate-200 bg-white px-4 py-6 transition-transform lg:translate-x-0 ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-10 flex items-center gap-3 px-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#ff6b35] text-lg font-black text-white">m</div><span className="text-xl font-bold tracking-tight">mumchies<span className="text-[#ff6b35]">.</span></span></div>
      <p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Workspace</p>
      <nav className="space-y-1">{nav.map(([icon, label]) => <button key={label} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${label === 'Orders' ? 'bg-orange-50 text-[#e95825]' : 'text-slate-500 hover:bg-slate-50'}`}><Icon name={icon}/>{label}{label === 'Orders' && <span className="ml-auto h-2 w-2 rounded-full bg-[#ff6b35]"/>}</button>)}</nav>
      <div className="mt-auto"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-slate-500 hover:bg-slate-50"><Icon name="settings"/>Settings</button><div className="mt-6 flex items-center gap-3 border-t border-slate-100 px-3 pt-5"><div className="grid h-9 w-9 place-items-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">AK</div><div><p className="text-sm font-semibold">Amit Kumar</p><p className="text-xs text-slate-400">Mumchies India</p></div></div></div>
    </aside>
    {sidebarOpen && <button aria-label="Close sidebar" onClick={() => setSidebarOpen(false)} className="fixed inset-0 z-20 bg-slate-900/20 lg:hidden"/>}
    <div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-5 backdrop-blur lg:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-slate-500 lg:hidden" onClick={() => setSidebarOpen(true)}><Icon name="menu"/></button><div><p className="text-sm font-medium text-slate-400">Welcome back, Amit</p><h1 className="text-xl font-bold tracking-tight">Orders</h1></div></div><div className="flex items-center gap-3"><button className="relative rounded-lg p-2 text-slate-500 hover:bg-slate-50"><Icon name="bell"/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#ff6b35]"/></button><div className="hidden h-8 w-px bg-slate-200 sm:block"/><button className="hidden items-center gap-2 text-sm font-medium sm:flex">This month <Icon name="chevron" size={15}/></button></div></header>
      <main className="p-5 lg:p-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-[#ff6b35]">Order management</p><h2 className="mt-1 text-2xl font-bold tracking-tight">All orders <span className="font-medium text-slate-400">({orders.length})</span></h2></div><button onClick={() => action('Order export is being prepared')} className="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 shadow-sm hover:bg-slate-50">Export orders</button></div>
        <section className="mb-7 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[{label:'New Orders',value:'128',hint:'+12.5%',tone:'text-blue-600',dot:'bg-blue-500'},{label:'Pending Booking',value:'34',hint:'Needs attention',tone:'text-amber-600',dot:'bg-amber-500'},{label:'COD',value:'₹84.2K',hint:'62 orders',tone:'text-violet-600',dot:'bg-violet-500'},{label:'Prepaid',value:'₹1.26L',hint:'66 orders',tone:'text-emerald-600',dot:'bg-emerald-500'},{label:'High Risk',value:'8',hint:'Review needed',tone:'text-rose-600',dot:'bg-rose-500'},{label:'Repeat Customers',value:'47',hint:'36.7% of orders',tone:'text-orange-600',dot:'bg-orange-500'}].map(card => <div key={card.label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-medium text-slate-500">{card.label}</p><span className={`h-2 w-2 rounded-full ${card.dot}`}/></div><p className="mt-3 text-2xl font-bold tracking-tight">{card.value}</p><p className={`mt-1 text-[11px] font-medium ${card.tone}`}>{card.hint}</p></div>)}</section>
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-4 xl:flex-row xl:items-center xl:justify-between"><div className="relative min-w-0 flex-1 xl:max-w-sm"><span className="absolute left-3 top-3 text-slate-400"><Icon name="search" size={17}/></span><input value={search} onChange={e => setSearch(e.target.value)} className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none placeholder:text-slate-400 focus:border-orange-300 focus:ring-2 focus:ring-orange-100" placeholder="Search by order, customer..."/></div><div className="flex flex-wrap items-center gap-2"><span className="hidden text-slate-400 md:block"><Icon name="filter" size={17}/></span><Filter value={payment} onChange={setPayment} options={['All payments', 'COD', 'Prepaid']}/><Filter value="All states" onChange={() => {}} options={['All states', 'Maharashtra', 'Karnataka', 'Delhi']}/><Filter value={risk} onChange={setRisk} options={['All risks', 'High', 'Medium', 'Low']}/><Filter value="All couriers" onChange={() => {}} options={['All couriers', 'Delhivery', 'Blue Dart', 'Ecom Express']}/><button className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-medium text-slate-600"><Icon name="calendar" size={16}/><span className="hidden sm:block">Date</span></button></div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-left"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wider text-slate-400"><tr>{['Order No','Date','Customer','City','State','Amount','Payment','Customer','Fastrr Risk','Recommended Courier','Status','Actions'].map(column => <th key={column} className="whitespace-nowrap px-4 py-3.5">{column}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(order => <OrderRow key={order.id} order={order} action={action}/>)}</tbody></table>{filtered.length === 0 && <div className="py-14 text-center text-sm text-slate-400">No orders match your filters.</div>}</div>
          <div className="flex items-center justify-between border-t border-slate-200 px-4 py-3"><p className="text-xs text-slate-500">Showing <span className="font-semibold text-slate-700">{filtered.length}</span> of {orders.length} orders</p><div className="flex gap-2"><button className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-400">Previous</button><button className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600">Next</button></div></div>
        </section></main>
    </div>{notice && <div className="fixed bottom-5 right-5 z-50 rounded-lg bg-slate-900 px-4 py-3 text-sm font-medium text-white shadow-xl">{notice}</div>}</div>
}

function Filter({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) { return <select value={value} onChange={e => onChange(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-medium text-slate-600 outline-none focus:border-orange-300">{options.map(option => <option key={option}>{option}</option>)}</select> }
function OrderRow({ order, action }: { order: Order; action: (message: string) => void }) { const status = order.status === 'New' ? 'bg-blue-50 text-blue-700' : order.status === 'Ready to book' ? 'bg-amber-50 text-amber-700' : order.status === 'Booked' ? 'bg-violet-50 text-violet-700' : 'bg-emerald-50 text-emerald-700'; return <tr className="text-sm text-slate-600 hover:bg-slate-50/70"><td className="px-4 py-3.5 font-semibold text-slate-800">{order.id}</td><td className="whitespace-nowrap px-4 py-3.5 text-xs">{order.date}</td><td className="px-4 py-3.5"><div className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-full bg-orange-100 text-[10px] font-bold text-orange-700">{order.initials}</span><span className="font-medium text-slate-700">{order.customer}</span></div></td><td className="px-4 py-3.5">{order.city}</td><td className="px-4 py-3.5">{order.state}</td><td className="px-4 py-3.5 font-semibold text-slate-800">₹{order.amount.toLocaleString('en-IN')}</td><td className="px-4 py-3.5"><span className={`rounded-md px-2 py-1 text-[11px] font-bold ${order.payment === 'COD' ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'}`}>{order.payment}</span></td><td className="px-4 py-3.5"><span className={`whitespace-nowrap rounded-md px-2 py-1 text-[11px] font-bold ${order.customerType === 'Repeat Customer' ? 'bg-violet-50 text-violet-700' : 'bg-slate-100 text-slate-600'}`}>{order.customerType}</span></td><td className="px-4 py-3.5"><span className={`rounded-md px-2 py-1 text-[11px] font-bold ring-1 ring-inset ${riskStyle[order.risk]}`}>{order.risk} Risk</span></td><td className="whitespace-nowrap px-4 py-3.5 text-xs font-medium">{order.courier}</td><td className="px-4 py-3.5"><span className={`whitespace-nowrap rounded-md px-2 py-1 text-[11px] font-bold ${status}`}>{order.status}</span></td><td className="px-4 py-3.5"><div className="flex items-center gap-1"><button onClick={() => action(`Viewing ${order.id}`)} title="View order" className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><Icon name="eye" size={16}/></button><button onClick={() => action(`Courier booking started for ${order.id}`)} title="Book courier" className="rounded-md p-1.5 text-slate-400 hover:bg-orange-50 hover:text-[#ff6b35]"><Icon name="truck" size={16}/></button><button title="More actions" className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100"><Icon name="more" size={16}/></button></div></td></tr> }
export default App
